FROM registry.access.redhat.com/ubi7-dev-preview/ubi-minimal:latest

LABEL maintainer "Devtools <devtools@redhat.com>"
LABEL author "Devtools <devtools@redhat.com>"

ENV BINARY=/usr/local/bin/run \
    USER_UID=1001 \
    USER_NAME=host-operator \
    LANG=en_US.utf8

# install operator binary
COPY bin/run ${BINARY}

USER ${USER_UID}

ENTRYPOINT [ "${BINARY}" ]
